In [ ]:
numpy 

In [ ]:
single dimensionL Array

In [1]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n1

array([10, 20, 30, 40, 50, 60])

In [4]:
n2 = np.array([[10,20,30,40,50,60],[30,44,22,55,67,76]])
print(n2)
n2
type(n2)


[[10 20 30 40 50 60]
 [30 44 22 55 67 76]]


numpy.ndarray

In [6]:
n3 = np.zeros((6,6))
n3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
n3 = np.full((6,6),12)
n3

array([[12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12]])

In [3]:
n4 = np.arange(10,20)
n4

In [18]:
n3 = np.random.randint(1,100,8)
n3

array([83, 14, 72, 62, 17,  3, 72, 32])

In [20]:
n3 = np.random.randint(1,100,31)
n3

array([94, 53, 11, 77, 83, 98, 71, 70, 96, 45, 98, 41, 31,  1, 28, 71, 25,
       10, 69, 23, 48, 56, 42,  5, 95, 93, 72, 45, 86, 39, 18])

In [23]:
n1 = np.array([[83, 14, 72, 62, 17,  3, 72, 32],[2,3,4,3,2,3,2,3]])
n1.shape
n1.shape = (8,2)
n1.shape
n1

array([[83, 14],
       [72, 62],
       [17,  3],
       [72, 32],
       [ 2,  3],
       [ 4,  3],
       [ 2,  3],
       [ 2,  3]])

In [24]:
n1 =np.array([83, 14, 72, 62, 17,  3, 72, 32])
n2 = np.array([84, 12, 72, 65, 17,  75, 73, 32])
np.vstack((n1,n2))


array([[83, 14, 72, 62, 17,  3, 72, 32],
       [84, 12, 72, 65, 17, 75, 73, 32]])

In [27]:
n1 =np.array([83, 14, 72, 62, 17,  3, 72, 32])
n2 = np.array([84, 12, 72, 65, 17,  75, 73, 32])
np.vstack((n2,n1))

array([[84, 12, 72, 65, 17, 75, 73, 32],
       [83, 14, 72, 62, 17,  3, 72, 32]])

In [28]:
n1 =np.array([83, 14, 72, 62, 17,  3, 72, 32])
n2 = np.array([84, 12, 72, 65, 17,  75, 73, 32])
np.hstack((n1,n2))

array([83, 14, 72, 62, 17,  3, 72, 32, 84, 12, 72, 65, 17, 75, 73, 32])

In [29]:
n1 =np.array([83, 14, 72, 62, 17,  3, 72, 32])
n2 = np.array([84, 12, 72, 65, 17,  75, 73, 32])
np.column_stack((n1,n2))

array([[83, 84],
       [14, 12],
       [72, 72],
       [62, 65],
       [17, 17],
       [ 3, 75],
       [72, 73],
       [32, 32]])

In [30]:
n1 =np.array([83, 14, 72, 62, 17,  3, 72, 32])
n2 = np.array([84, 12, 72, 65, 17,  75, 73, 32])
np.intersect1d(n1,n2)

array([17, 32, 72])

In [31]:
n1 =np.array([83, 14, 72, 62, 17,  3, 72, 32])
n2 = np.array([84, 12, 72, 65, 17,  75, 73, 32])
np.setdiff1d(n1,n2)

array([ 3, 14, 62, 83])

In [32]:
n1 =np.array([83, 14, 72, 62, 17,  3, 72, 32])
n2 = np.array([84, 12, 72, 65, 17,  75, 73, 32])
np.sum([n1,n2])

785

In [48]:
n1 =np.array([83, 14, 72, 62, 17,  3, 72, 32])
n2 = np.array([84, 12, 72, 65, 17,  75, 73, 32])
n3 = np.vstack((n2,n1))
n3.sum(axis =1)



array([430, 355])

In [49]:
n1 =np.array([83, 14, 72, 62, 17,  3, 72, 32])
n2 = np.array([84, 12, 72, 65, 17,  75, 73, 32])
np.sum([n1,n2],axis=0)
n1 = n1+2
n1

array([85, 16, 74, 64, 19,  5, 74, 34])

In [50]:
n2 = n2*2
n2

array([168,  24, 144, 130,  34, 150, 146,  64])

In [55]:
n4 = np.array([2,9,7,4,3,3,5,4,3,3,])
np.save('my_np', n4)

In [1]:
n5=np.load('my_np',n4)
n5